[package]
name = "pikadick"
version = "0.0.0"
authors = [ "professionalProgrammers <rusty.bois.bios.rusty@gmail.com>" ]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bincode = "1.3.1"
chrono = "0.4.19"
crossbeam = "0.8.0"
dashmap = "4.0.1" # 4.0.0-rc6
fml = { path = "./lib/fml-rs" }
futures = { version = "0.3.8", default-features = false }
heim = { version = "0.1.0-beta.3", features = [ "host", "cpu", "virt", "memory" ] }
indexmap = "1.6.0"
insta = { path = "./lib/insta-rs" }
lazy_static = "1.4.0"
nekos = { path = "./lib/nekos-rs" }
parking_lot = "0.11.1"
polldaddy = { git = "https://github.com/adumbidiot/polldaddy-rs", rev = "990fa0b" }
quizizz = { path = "./lib/quizizz-rs" }
r6stats = { path = "./lib/r6stats-rs" }
r6tracker = { path = "./lib/r6tracker-rs" }
rand = "0.7.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "e7e21b3" }
reddit-tube = { path = "./lib/reddit-tube-rs" }
regex = "1.3.9"
rule34 = { path = "./lib/rule34-rs" }
serde = { version = "1.0.118", features = [ "derive" ] }
serenity = "0.9.1"
shift-orcz = { git = "https://github.com/adumbidiot/shift-client-rs", rev = "774f36b" } 
slog = "2.7.0"
slog-async = "2.5.0"
slog-term = "2.6.0"
sqlx = { version = "0.3.5", default-features = false, features = [ "runtime-tokio", "macros", "sqlite" ] }
systemstat = "0.1.5"
thiserror = "1.0.22"
tokio = { version = "0.2.22", features = [ "parking_lot", "sync", "rt-core", "rt-threaded", "time", "signal" ] }
toml = "0.5.6"
uom = "0.30.0"
url = "2.1.1"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

# Optional
openssl = { version = "0.10", optional = true, features = [ "vendored" ] }

[features]
# Note: This is needed for cross comp as sqlx has a hard, non-optional dependency on native-tls
use-openssl-vendored = [ "openssl" ]

[workspace]
members = [ 
	"lib/fml-rs",
	"lib/nekos-rs", 
	"lib/quizizz-rs",
	"lib/r6stats-rs", 
	"lib/r6tracker-rs", 
	"lib/reddit-tube-rs",
	"lib/rule34-rs",
    "lib/insta-rs",
]
