[package]
name = "pikadick"
version = "0.0.0"
authors = [ "professionalProgrammers <rusty.bois.bios.rusty@gmail.com>" ]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1.0.40"
bincode = "1.3.2"
chrono = "0.4.19"
crossbeam = "0.8.0"
dashmap = "4.0.2"
deviantart = { path = "./lib/deviantart-rs" }
fern = { version = "0.6.0", features = [ "colored" ] }
fml = { path = "./lib/fml-rs" }
futures = { version = "0.3.13", default-features = false }
heim = { version = "0.1.0-rc.1", features = [ "host", "cpu", "virt", "memory" ] }
indexmap = "1.6.2"
insta = { path = "./lib/insta-rs" }
lazy_static = "1.4.0"
log = "0.4.14"
minimax = { path = "./lib/minimax-rs" }
nekos = { path = "./lib/nekos-rs" }
parking_lot = "0.11.1"
quizizz = { path = "./lib/quizizz-rs" }
r6stats = { path = "./lib/r6stats-rs" }
r6tracker = { path = "./lib/r6tracker-rs" }
rand = "0.8.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "b7e79ccd5451be21540d54d5cff2cf76749a753a" }
reddit-tube = { path = "./lib/reddit-tube-rs" }
regex = "1.4.5"
rule34 = { path = "./lib/rule34-rs" }
serde = { version = "1.0.125", features = [ "derive" ] }
serenity = "0.10.4"
shift-orcz = { git = "https://github.com/adumbidiot/shift-client-rs", rev = "04e43f0670a681129164ac0ef90c898cdbb6695a" } 
sqlx = { version = "0.5.1", features = [ "sqlite", "runtime-tokio-rustls" ] }
systemstat = "0.1.7"
thiserror = "1.0.24"
tiny-skia = { version = "0.5.1", features = [ "std", "simd", "png-format" ], default-features = false }
tokio = { version = "1.4.0", features = [ "rt-multi-thread", "signal", "sync", "time", "parking_lot" ] }
toml = "0.5.8"
ttf-parser = "0.12.0"
uom = "0.30.0"
urban-dictionary = { path = "./lib/urban-dictionary-rs" }
url = "2.2.1"
xkcd = { path = "lib/xkcd-rs" }
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "a5e0ce60cb37daee1f4b954c5270c30d1034c4af" }

# Optional
openssl = { version = "0.10.33", optional = true, features = [ "vendored" ] }

[features]
# Note: This is needed for cross comp as sqlx has a hard, non-optional dependency on native-tls
use-openssl-vendored = [ "openssl" ]

[patch.crates-io]
# Fix security advisory
heim = { git = "https://github.com/heim-rs/heim", branch = "dependabot/cargo/raw-cpuid-approx-9.0" }

[workspace]
members = [ 
	"lib/fml-rs",
	"lib/nekos-rs", 
	"lib/quizizz-rs",
	"lib/r6stats-rs", 
	"lib/r6tracker-rs", 
	"lib/reddit-tube-rs",
	"lib/rule34-rs",
    "lib/insta-rs",
    "lib/deviantart-rs",
    "lib/urban-dictionary-rs",
    "lib/xkcd-rs",
    "lib/tiktock-rs",
    "lib/minimax-rs",
    "lib/open-graph-rs",
]

# To make image drawing times sane
[profile.dev.package.tiny-skia]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.png]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.miniz_oxide]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.crc32fast]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.deflate]
opt-level = 3
