[package]
name = "pikadick"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.51"
async-rusqlite = { path = "./lib/async-rusqlite-rs", features = [ "bundled" ] }
bincode = "1.3.3"
chrono = "0.4.19"
crossbeam = "0.8.1"
dashmap = "4.0.2"
deviantart = { path = "./lib/deviantart-rs" }
fml = { path = "./lib/fml-rs" }
heim = { version = "0.1.0-rc.1", features = [ "host", "cpu", "virt", "memory" ] }
indexmap = "1.7.0"
insta = { path = "./lib/insta-rs" }
iqdb = { path = "./lib/iqdb-rs" }
itoa = "0.4.8"
lazy_static = "1.4.0"
nekos = { path = "./lib/nekos-rs" }
once_cell = "1.8.0"
opentelemetry = { version = "0.16.0", features = [ "rt-tokio" ] }
opentelemetry-otlp = { version = "0.9.0", features = [ "tls", "tls-roots" ] }
parking_lot = "0.11.2"
quizizz = { path = "./lib/quizizz-rs" }
r6stats = { path = "./lib/r6stats-rs" }
r6tracker = { path = "./lib/r6tracker-rs" }
rand = "0.8.4"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "d46d78445ca94023aee417fe92bd43e86faf36dc", features = [ "force-rustls-tls" ] }
reddit-tube = { path = "./lib/reddit-tube-rs" }
regex = "1.5.4"
rule34 = { path = "./lib/rule34-rs" }
rusqlite = { version = "0.26.3", features = [ "bundled", "blob", "trace" ] }
serde = { version = "1.0.131", features = [ "derive" ] }
serenity = { version = "0.10.9", features = [ "client", "standard_framework", "voice" ] }
shift-orcz = { git = "https://github.com/adumbidiot/shift-client-rs", rev = "f131491d81042c0858ec781ae1f2ac6cbe7ef68a" } 
songbird = "0.2.0"
systemstat = "0.1.10"
thiserror = "1.0.30"
tic-tac-toe = { path = "lib/tic-tac-toe-rs" }
tiny-skia = { version = "0.6.1", features = [ "std", "simd", "png-format" ], default-features = false }
tokio = { version = "1.15.0", features = [ "rt-multi-thread", "signal", "sync", "time", "parking_lot" ] }
toml = "0.5.8"
tonic = "0.5.1"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-log = "0.1.2"
tracing-opentelemetry = "0.16.0"
tracing-subscriber = { version = "0.3.3", features = [ "env-filter", "fmt", "parking_lot" ] }
ttf-parser = "0.13.4"
uom = "0.31.1"
urban-dictionary = { path = "./lib/urban-dictionary-rs" }
url = "2.2.2"
xkcd = { path = "lib/xkcd-rs" }
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "a5e0ce60cb37daee1f4b954c5270c30d1034c4af" }

# Optional
openssl = { version = "0.10.38", optional = true, features = [ "vendored" ] }

[features]
# Note: This is needed for cross comp
use-openssl-vendored = [ "openssl" ]

[patch.crates-io]
# Fix security advisory.
heim = { git = "https://github.com/heim-rs/heim", rev = "b292f1535bb27c03800cdb7509fa81a40859fbbb" }

# `servo_arc` has UB on crates.io. This still has UB, but less and I haven't seen any issues with it yet.
# To fix this, I think https://doc.rust-lang.org/std/mem/fn.size_of_val_raw.html needs to stabilize.
servo_arc = { git = "https://github.com/servo/servo", rev = "490c215798a92aca1468a1767e3cc294f824036c" }

[workspace]
members = [ 
    "lib/fml-rs",
    "lib/nekos-rs", 
    "lib/quizizz-rs",
    "lib/r6stats-rs", 
    "lib/r6tracker-rs", 
    "lib/reddit-tube-rs",
    "lib/rule34-rs",
    "lib/insta-rs",
    "lib/deviantart-rs",
    "lib/urban-dictionary-rs",
    "lib/xkcd-rs",
    "lib/tiktok-rs",
    "lib/open-graph-rs",
    "lib/iqdb-rs",
    "lib/sauce-nao-rs",
    "lib/tic-tac-toe-rs",
    "lib/async-rusqlite-rs",
]

# To make image drawing times sane
[profile.dev.package.tiny-skia]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.png]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.miniz_oxide]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.crc32fast]
opt-level = 3

# To make image encoding times sane
[profile.dev.package.deflate]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
