[package]
name = "pikadick"
version = "0.0.0"
authors = [ "professionalProgrammers <rusty.bois.bios.rusty@gmail.com>" ]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bincode = "1.3.1"
chrono = "0.4.19"
crossbeam = "0.7.3"
dashmap = "4.0.1"
fml = { path = "./lib/fml-rs" }
futures = { version = "0.3.8", default-features = false }
heim = { version = "0.1.0-beta.3", features = [ "host", "cpu", "virt", "memory" ] }
indexmap = "1.6.0"
insta = { path = "./lib/insta-rs" }
lazy_static = "1.4.0"
nekos = { path = "./lib/nekos-rs" }
parking_lot = "0.11.1"
polldaddy = { git = "https://github.com/adumbidiot/polldaddy-rs", rev = "4a214c9e07a6783a6375d79de0d1430afd6c18ee" }
quizizz = { path = "./lib/quizizz-rs" }
r6stats = { path = "./lib/r6stats-rs" }
r6tracker = { path = "./lib/r6tracker-rs" }
rand = "0.7.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "b7e79ccd5451be21540d54d5cff2cf76749a753a" }
reddit-tube = { path = "./lib/reddit-tube-rs" }
regex = "1.3.9"
rule34 = { path = "./lib/rule34-rs" }
serde = { version = "1.0.118", features = [ "derive" ] }
serenity = "0.10.0"
shift-orcz = { git = "https://github.com/adumbidiot/shift-client-rs", rev = "95ad3c3db461d0d39efff31bd91a091901c7c7db" } 
slog = "2.7.0"
slog-async = "2.5.0"
slog-term = "2.6.0"
# Use runtime-async-std-rustls to not use 2 versions of tokio
sqlx = { version = "0.4.2", features = [ "sqlite", "runtime-async-std-rustls" ] }
systemstat = "0.1.5"
thiserror = "1.0.22"
tokio = { version = "1.0.1", features = [ "parking_lot", "sync", "rt-multi-thread", "time", "signal" ] }
toml = "0.5.6"
uom = "0.30.0"
url = "2.1.1"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

# Optional
openssl = { version = "0.10", optional = true, features = [ "vendored" ] }

[features]
# Note: This is needed for cross comp as sqlx has a hard, non-optional dependency on native-tls
use-openssl-vendored = [ "openssl" ]

[patch.crates-io]

[workspace]
members = [ 
	"lib/fml-rs",
	"lib/nekos-rs", 
	"lib/quizizz-rs",
	"lib/r6stats-rs", 
	"lib/r6tracker-rs", 
	"lib/reddit-tube-rs",
	"lib/rule34-rs",
    "lib/insta-rs",
]
