# This is the cross compile config for CI.
[armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
cmake_toolchain_file = """
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_FLAGS "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -fPIC")
"""

[armv7-unknown-linux-gnueabihf.env]
CC = "arm-linux-gnueabihf-gcc"
CXX = "arm-linux-gnueabihf-g++"

# CMAKE_GENERATOR = "Ninja"