# This is the cross compile config for CI.
[armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
cmake_toolchain_file = """
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_FLAGS "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -fPIC")
"""

[armv7-unknown-linux-gnueabihf.env]
# This is empty as the default env is fine.
# The default perl does not need to be overridden.

CMAKE_GENERATOR = "Ninja"