targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "ISC", "Unlicense", "Zlib", "BSD-2-Clause", "BSD-3-Clause" ]
exceptions = [
    { name = "webpki-roots", allow = [ "MPL-2.0" ] },
    { name = "wepoll-sys", allow = [ "MPL-2.0" ] },
    { name = "ring", allow = [ "MIT", "ISC", "OpenSSL" ] },
    { name = "colored", allow = [ "MPL-2.0" ] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "deny"
highlight = "all"
skip = [    
    # Blocked on chrono, systemstat, and xml5ever bumping time to 0.2.16
    { name = "time", version = "0.1.43" },
    
    # Blocked on rand updating getrandom to 0.2.x 
    { name = "getrandom", version = "0.1.15" },
    
    # Blocked on rustls, and tungstentite bumping base64 to 0.13.x
    { name = "base64", version = "0.12.3" },
    
    # Blocked on async-tungstenite updating webpki-roots to 0.21.x
    { name = "webpki-roots", version = "0.20.0" },
    
    # Blocked on phf_generator, tempfile, tungstenite, and zalgo moving to rand 0.8.x
    { name = "rand", version = "0.7.3" },
    { name = "rand_core", version = "0.5.1" },
    { name = "rand_chacha", version = "0.2.2" },
    
    # Blocked on input_buffer and sqlx moving to bytes 1.0.x
    { name = "bytes", version = "0.5.6" },
    
    # Blocked on hashbrown updating ahash to 0.4.7
    { name = "ahash", version = "0.4.7" },
    
    # Blocked on hyper and mio updating `socket` to `0.3.0`
    { name = "socket2", version = "0.3.0" },
]

# Mostly soundness denies since the advisory lacks a section for soundess bugs
deny = [
    # https://github.com/RustSec/advisory-db/issues/298
    { name = "linked-hash-map", version = "<0.5.3" },
    
    # https://github.com/RustSec/advisory-db/pull/290
    { name = "bigint", version = "*" },
    
    # https://github.com/RustSec/advisory-db/pull/293
    # NOTE: May be sound in the future: https://github.com/RustSec/advisory-db/pull/293#issuecomment-641898680
    { name = "rio", version = "*" },

    # https://github.com/RustSec/advisory-db/issues/299
    { name = "smallvec", version = "<0.6.13" },
    
    # https://github.com/RustSec/advisory-db/pull/268
    { name = "plutonium", version = "*" },
    
    # https://github.com/RustSec/advisory-db/pull/308
    { name = "traitobject", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/305
    { name = "rental", version = "*" },
    
    # Appears to be moving towards integrating rio more tightly for io_uring support
    { name = "sled", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = [
    "https://github.com/adumbidiot/zalgo-rs",
    "https://github.com/adumbidiot/shift-client-rs",
    "https://github.com/adumbidiot/reddit-rs",
    "https://github.com/heim-rs/heim",
]
