targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "armv7-unknown-linux-gnueabihf" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = [
    # Blocked on updating `chrono` and `systemstat`.
    # We don't mess with the env much so this should't be too much of an issue.
    "RUSTSEC-2020-0071",
    
    # Blocked on tracing removing `chrono`
    "RUSTSEC-2020-0159",
    
    # Blocked on criterion moving away from "serde_cbor". This is fine as criterion is a dev-dependency.
    "RUSTSEC-2021-0127",
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "ISC", "Unlicense", "Zlib", "BSD-2-Clause", "BSD-3-Clause", "MPL-2.0", "CC0-1.0" ]
exceptions = [
    { name = "ring", allow = [ "MIT", "ISC", "OpenSSL" ] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "encoding_rs"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[bans]
multiple-versions = "deny"
highlight = "all"
skip = [    
    # Blocked on chrono, systemstat, and xml5ever bumping time to 0.2.16
    { name = "time", version = "0.1.43" },
    
    # Blocked on rand updating getrandom to 0.2.x 
    { name = "getrandom", version = "0.1.15" },
    
    # Blocked on phf_generator, tempfile, tungstenite, and zalgo moving to rand 0.8.x
    { name = "rand", version = "0.7.3" },
    { name = "rand_core", version = "0.5.1" },
    { name = "rand_chacha", version = "0.2.2" },
    
    # Blocked on reqwest updating webpki
    { name = "webpki", version = "0.21.4" },
    
    # Blocked on async-tungstenite and tonic updating tokio-rustls to 0.23.1 and rustls to 0.20.x
    { name = "tokio-rustls", version = "0.22.0" },
    { name = "rustls", version = "0.19.1" },
    { name = "sct", version = "0.6.1" },
    
    # Blocked on ring updating their version of spin to 0.9
    { name = "spin", version = "0.9.2" },
    
    # Blocked on serenity-voice-model moving away from enum_primitive
    { name = "num-traits", version = "0.1.43" },
    
    # Blocked on songbird updating symphonia-core to 0.4.0
    { name = "arrayvec", version = "0.4.12" },
    
    # Blocked on serenity updating tungstenite to 0.16.0
    { name = "tungstenite", version = "0.13.0" },
    { name = "webpki-roots", version = "0.21.1" },
    { name = "async-tungstenite", version = "0.14.0" },
    
    # Blocked on time getting updated from a lot of crates 
    { name = "time", version = "0.2.27" },  
    
    # Blocked on a lot of crates moving to version 1. Re-evaluate in like a month or two. 12/7/2021.
    { name = "itoa", version = "0.4.8" },
    
    # Blocked on songbird updating to 5.0.0
    { name = "dashmap", version = "4.0.2" },
    
    # Blocked on updates to cssparser
    { name = "phf_shared", version = "0.8.0" },
]

# Mostly soundness denies since the advisory lacks a section for soundess bugs
deny = [            
    # https://github.com/RustSec/advisory-db/issues/305
    { name = "rental", version = "*" },
    
    # This is basically Rust written like C.
    { name = "sled", version = "*" },
    
    # The general idea seems unsound, and the current version does contain UB.
    # https://github.com/Kimundi/owning-ref-rs/issues/71
    { name = "owning_ref", version = "*" },
    
    # It's a crate only intended for testing; people insist on using it for some reason.
    # https://crates.io/crates/markup5ever_rcdom/0.1.0
    { name = "markup5ever_rcdom", version = "0.1.0" },
    
    # https://github.com/RustSec/advisory-db/issues/867
    { name = "rusttype", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/826
    { name = "totally-safe-transmute", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/743
    { name = "fast-floats", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/913
    { name = "hexchat", version = ">=0.3.0" },
    
    # https://github.com/RustSec/advisory-db/issues/613
    { name = "out-reference", version = "*" },
    
    # https://github.com/rustsec/advisory-db/issues/1175
    { name = "futures-intrusive", version = "*" },
    
    # Probably abandoned. Commented as it is used by `tracing-subscriber`.
    # https://github.com/rustsec/advisory-db/issues/1095
    # { name = "ansi_term", version = "*" },
    
    # https://github.com/rustsec/advisory-db/issues/1173
    { name = "prettytables-rs", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = [
    "https://github.com/adumbidiot/zalgo-rs",
    "https://github.com/adumbidiot/shift-client-rs",
    "https://github.com/adumbidiot/reddit-rs",
    # "https://github.com/heim-rs/heim",
    "https://github.com/servo/servo",
    "https://github.com/adumbidiot/songbird",
    "https://github.com/serenity-rs/serenity",
    "https://github.com/vectordotdev/heim",
]
