[tasks.setup-cross]
workspace = false
install_crate = { crate_name = "across", binary = "across", test_arg = "help" }
install_crate_args = [ 
    "--git", "https://github.com/adumbidiot/pikadick-rs", 
    "--bin", "across",
]

[tasks.setup-cargo-deb]
workspace = false
install_crate = { crate_name = "cargo-deb", binary = "cargo-deb", test_arg = "--help" }

[tasks.setup-rpi-deploy]
workspace = false
install_crate = { crate_name = "rpi-deploy", binary = "rpi-deploy", test_arg = "help" }
install_crate_args = [ 
    "--git", "https://github.com/adumbidiot/pikadick-rs", 
    "--bin", "rpi-deploy",
    "rpi-deploy",
]

[tasks.pkg]
workspace = false
command = "rpi-deploy"
args = [
    "package",
]
dependencies = [
    "setup-cargo-deb",
    "setup-rpi-deploy",
]

[tasks.deploy]
workspace = false
command = "rpi-deploy"
args = [ 
    "deploy",
    "--name", "${@}",
]
dependencies = [
    "setup-cross",
    "setup-cargo-deb",
    "setup-rpi-deploy",
]