name: BuildRpi
on:
  push:
    branches:
      - master
  
jobs:
  build-rpi:
    name: Build Rpi
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-unknown-linux-gnueabihf
        profile: minimal
        override: true
        components: rustfmt, rust-src
        
    - name: Update Package Lists
      run: sudo apt-get update

    - name: Install GCC Cross Compilation Toolchain
      run: sudo apt-get install gcc-arm-linux-gnueabihf
      
    - name: Install Python Deps
      run: |
          python -m pip install --upgrade pip
          pip install tomli
          
    - name: Install `cargo-deb`
      run: cargo install cargo-deb

    - name: Build
      run: make pkg
      
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: pikadick
        path: target/armv7-unknown-linux-gnueabihf/release/pikadick
