name: Rust
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-lint-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install Protobuf Compiler
        run: sudo apt-get install -y protobuf-compiler
      
      - name: Clippy
        run: cargo clippy --tests --all --all-features -- -D warnings
        
  # We use nightly options for formatting,
  # so split linting to add freedom to choose toolchains for the rest of the linting steps.       
  lint-rustfmt:
    name: Lint RustFmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-lint-rustfmt-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install Nightly RustFmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          
      - name: RustFmt
        run: cargo fmt -- --check --color always
          
  Deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v2
        
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-cargo-${{ hashFiles('**/Cargo.lock') }}
            
      - name: Run `apt-get update`
        run: sudo apt-get update
            
      - name: Install FFMpeg
        run: sudo apt-get install -y ffmpeg
        
      - name: Install Protobuf Compiler
        run: sudo apt-get install -y protobuf-compiler
        
      - name: Build Pikadick
        run: cargo build --verbose
        
      - name: Build All
        run: cargo build --verbose --all --all-features
        
      - name: Run Tests
        run: cargo test --all --verbose
        
      - name: Build Docs
        run: cargo doc --verbose --all
